// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.peigongdh.apidoc.register;

public final class RegisterProto {
  private RegisterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code register.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GATE_CONNECT = 0;</code>
     */
    GATE_CONNECT(0),
    /**
     * <code>INNER_CONNECT = 1;</code>
     */
    INNER_CONNECT(1),
    /**
     * <code>BROADCAST_ADDRESS = 2;</code>
     */
    BROADCAST_ADDRESS(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GATE_CONNECT = 0;</code>
     */
    public static final int GATE_CONNECT_VALUE = 0;
    /**
     * <code>INNER_CONNECT = 1;</code>
     */
    public static final int INNER_CONNECT_VALUE = 1;
    /**
     * <code>BROADCAST_ADDRESS = 2;</code>
     */
    public static final int BROADCAST_ADDRESS_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return GATE_CONNECT;
        case 1: return INNER_CONNECT;
        case 2: return BROADCAST_ADDRESS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.peigongdh.apidoc.register.RegisterProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:register.EventType)
  }

  public interface ConnectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:register.Connect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.register.EventType event = 1;</code>
     */
    int getEventValue();
    /**
     * <code>.register.EventType event = 1;</code>
     */
    com.peigongdh.apidoc.register.RegisterProto.EventType getEvent();

    /**
     * <code>string Address = 2;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string Address = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code register.Connect}
   */
  public  static final class Connect extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:register.Connect)
      ConnectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Connect.newBuilder() to construct.
    private Connect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Connect() {
      event_ = 0;
      address_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Connect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              event_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_Connect_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_Connect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.peigongdh.apidoc.register.RegisterProto.Connect.class, com.peigongdh.apidoc.register.RegisterProto.Connect.Builder.class);
    }

    public static final int EVENT_FIELD_NUMBER = 1;
    private int event_;
    /**
     * <code>.register.EventType event = 1;</code>
     */
    public int getEventValue() {
      return event_;
    }
    /**
     * <code>.register.EventType event = 1;</code>
     */
    public com.peigongdh.apidoc.register.RegisterProto.EventType getEvent() {
      @SuppressWarnings("deprecation")
      com.peigongdh.apidoc.register.RegisterProto.EventType result = com.peigongdh.apidoc.register.RegisterProto.EventType.valueOf(event_);
      return result == null ? com.peigongdh.apidoc.register.RegisterProto.EventType.UNRECOGNIZED : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object address_;
    /**
     * <code>string Address = 2;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string Address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (event_ != com.peigongdh.apidoc.register.RegisterProto.EventType.GATE_CONNECT.getNumber()) {
        output.writeEnum(1, event_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (event_ != com.peigongdh.apidoc.register.RegisterProto.EventType.GATE_CONNECT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, event_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.peigongdh.apidoc.register.RegisterProto.Connect)) {
        return super.equals(obj);
      }
      com.peigongdh.apidoc.register.RegisterProto.Connect other = (com.peigongdh.apidoc.register.RegisterProto.Connect) obj;

      boolean result = true;
      result = result && event_ == other.event_;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + event_;
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.Connect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.peigongdh.apidoc.register.RegisterProto.Connect prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code register.Connect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:register.Connect)
        com.peigongdh.apidoc.register.RegisterProto.ConnectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_Connect_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_Connect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.peigongdh.apidoc.register.RegisterProto.Connect.class, com.peigongdh.apidoc.register.RegisterProto.Connect.Builder.class);
      }

      // Construct using com.peigongdh.apidoc.register.RegisterProto.Connect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        event_ = 0;

        address_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_Connect_descriptor;
      }

      @java.lang.Override
      public com.peigongdh.apidoc.register.RegisterProto.Connect getDefaultInstanceForType() {
        return com.peigongdh.apidoc.register.RegisterProto.Connect.getDefaultInstance();
      }

      @java.lang.Override
      public com.peigongdh.apidoc.register.RegisterProto.Connect build() {
        com.peigongdh.apidoc.register.RegisterProto.Connect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.peigongdh.apidoc.register.RegisterProto.Connect buildPartial() {
        com.peigongdh.apidoc.register.RegisterProto.Connect result = new com.peigongdh.apidoc.register.RegisterProto.Connect(this);
        result.event_ = event_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.peigongdh.apidoc.register.RegisterProto.Connect) {
          return mergeFrom((com.peigongdh.apidoc.register.RegisterProto.Connect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.peigongdh.apidoc.register.RegisterProto.Connect other) {
        if (other == com.peigongdh.apidoc.register.RegisterProto.Connect.getDefaultInstance()) return this;
        if (other.event_ != 0) {
          setEventValue(other.getEventValue());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.peigongdh.apidoc.register.RegisterProto.Connect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.peigongdh.apidoc.register.RegisterProto.Connect) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int event_ = 0;
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public int getEventValue() {
        return event_;
      }
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public Builder setEventValue(int value) {
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public com.peigongdh.apidoc.register.RegisterProto.EventType getEvent() {
        @SuppressWarnings("deprecation")
        com.peigongdh.apidoc.register.RegisterProto.EventType result = com.peigongdh.apidoc.register.RegisterProto.EventType.valueOf(event_);
        return result == null ? com.peigongdh.apidoc.register.RegisterProto.EventType.UNRECOGNIZED : result;
      }
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public Builder setEvent(com.peigongdh.apidoc.register.RegisterProto.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        event_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public Builder clearEvent() {
        
        event_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string Address = 2;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Address = 2;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Address = 2;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string Address = 2;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:register.Connect)
    }

    // @@protoc_insertion_point(class_scope:register.Connect)
    private static final com.peigongdh.apidoc.register.RegisterProto.Connect DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.peigongdh.apidoc.register.RegisterProto.Connect();
    }

    public static com.peigongdh.apidoc.register.RegisterProto.Connect getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Connect>
        PARSER = new com.google.protobuf.AbstractParser<Connect>() {
      @java.lang.Override
      public Connect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Connect(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Connect> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Connect> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.peigongdh.apidoc.register.RegisterProto.Connect getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BroadcastAddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:register.BroadcastAddress)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.register.EventType event = 1;</code>
     */
    int getEventValue();
    /**
     * <code>.register.EventType event = 1;</code>
     */
    com.peigongdh.apidoc.register.RegisterProto.EventType getEvent();

    /**
     * <code>repeated string addresses = 2;</code>
     */
    java.util.List<java.lang.String>
        getAddressesList();
    /**
     * <code>repeated string addresses = 2;</code>
     */
    int getAddressesCount();
    /**
     * <code>repeated string addresses = 2;</code>
     */
    java.lang.String getAddresses(int index);
    /**
     * <code>repeated string addresses = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressesBytes(int index);
  }
  /**
   * Protobuf type {@code register.BroadcastAddress}
   */
  public  static final class BroadcastAddress extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:register.BroadcastAddress)
      BroadcastAddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BroadcastAddress.newBuilder() to construct.
    private BroadcastAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BroadcastAddress() {
      event_ = 0;
      addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BroadcastAddress(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              event_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                addresses_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              addresses_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          addresses_ = addresses_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_BroadcastAddress_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_BroadcastAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress.class, com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress.Builder.class);
    }

    private int bitField0_;
    public static final int EVENT_FIELD_NUMBER = 1;
    private int event_;
    /**
     * <code>.register.EventType event = 1;</code>
     */
    public int getEventValue() {
      return event_;
    }
    /**
     * <code>.register.EventType event = 1;</code>
     */
    public com.peigongdh.apidoc.register.RegisterProto.EventType getEvent() {
      @SuppressWarnings("deprecation")
      com.peigongdh.apidoc.register.RegisterProto.EventType result = com.peigongdh.apidoc.register.RegisterProto.EventType.valueOf(event_);
      return result == null ? com.peigongdh.apidoc.register.RegisterProto.EventType.UNRECOGNIZED : result;
    }

    public static final int ADDRESSES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList addresses_;
    /**
     * <code>repeated string addresses = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddressesList() {
      return addresses_;
    }
    /**
     * <code>repeated string addresses = 2;</code>
     */
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <code>repeated string addresses = 2;</code>
     */
    public java.lang.String getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <code>repeated string addresses = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressesBytes(int index) {
      return addresses_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (event_ != com.peigongdh.apidoc.register.RegisterProto.EventType.GATE_CONNECT.getNumber()) {
        output.writeEnum(1, event_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addresses_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (event_ != com.peigongdh.apidoc.register.RegisterProto.EventType.GATE_CONNECT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, event_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addresses_.size(); i++) {
          dataSize += computeStringSizeNoTag(addresses_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddressesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress)) {
        return super.equals(obj);
      }
      com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress other = (com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress) obj;

      boolean result = true;
      result = result && event_ == other.event_;
      result = result && getAddressesList()
          .equals(other.getAddressesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + event_;
      if (getAddressesCount() > 0) {
        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getAddressesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code register.BroadcastAddress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:register.BroadcastAddress)
        com.peigongdh.apidoc.register.RegisterProto.BroadcastAddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_BroadcastAddress_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_BroadcastAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress.class, com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress.Builder.class);
      }

      // Construct using com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        event_ = 0;

        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.peigongdh.apidoc.register.RegisterProto.internal_static_register_BroadcastAddress_descriptor;
      }

      @java.lang.Override
      public com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress getDefaultInstanceForType() {
        return com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress.getDefaultInstance();
      }

      @java.lang.Override
      public com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress build() {
        com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress buildPartial() {
        com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress result = new com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.event_ = event_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          addresses_ = addresses_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.addresses_ = addresses_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress) {
          return mergeFrom((com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress other) {
        if (other == com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress.getDefaultInstance()) return this;
        if (other.event_ != 0) {
          setEventValue(other.getEventValue());
        }
        if (!other.addresses_.isEmpty()) {
          if (addresses_.isEmpty()) {
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAddressesIsMutable();
            addresses_.addAll(other.addresses_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int event_ = 0;
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public int getEventValue() {
        return event_;
      }
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public Builder setEventValue(int value) {
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public com.peigongdh.apidoc.register.RegisterProto.EventType getEvent() {
        @SuppressWarnings("deprecation")
        com.peigongdh.apidoc.register.RegisterProto.EventType result = com.peigongdh.apidoc.register.RegisterProto.EventType.valueOf(event_);
        return result == null ? com.peigongdh.apidoc.register.RegisterProto.EventType.UNRECOGNIZED : result;
      }
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public Builder setEvent(com.peigongdh.apidoc.register.RegisterProto.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        event_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.register.EventType event = 1;</code>
       */
      public Builder clearEvent() {
        
        event_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          addresses_ = new com.google.protobuf.LazyStringArrayList(addresses_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddressesList() {
        return addresses_.getUnmodifiableView();
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public int getAddressesCount() {
        return addresses_.size();
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public java.lang.String getAddresses(int index) {
        return addresses_.get(index);
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressesBytes(int index) {
        return addresses_.getByteString(index);
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder setAddresses(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder addAddresses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder clearAddresses() {
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder addAddressesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:register.BroadcastAddress)
    }

    // @@protoc_insertion_point(class_scope:register.BroadcastAddress)
    private static final com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress();
    }

    public static com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BroadcastAddress>
        PARSER = new com.google.protobuf.AbstractParser<BroadcastAddress>() {
      @java.lang.Override
      public BroadcastAddress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadcastAddress(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BroadcastAddress> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BroadcastAddress> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.peigongdh.apidoc.register.RegisterProto.BroadcastAddress getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_register_Connect_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_register_Connect_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_register_BroadcastAddress_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_register_BroadcastAddress_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016register.proto\022\010register\">\n\007Connect\022\"\n" +
      "\005event\030\001 \001(\0162\023.register.EventType\022\017\n\007Add" +
      "ress\030\002 \001(\t\"I\n\020BroadcastAddress\022\"\n\005event\030" +
      "\001 \001(\0162\023.register.EventType\022\021\n\taddresses\030" +
      "\002 \003(\t*G\n\tEventType\022\020\n\014GATE_CONNECT\020\000\022\021\n\r" +
      "INNER_CONNECT\020\001\022\025\n\021BROADCAST_ADDRESS\020\002B." +
      "\n\035com.peigongdh.apidoc.registerB\rRegiste" +
      "rProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_register_Connect_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_register_Connect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_register_Connect_descriptor,
        new java.lang.String[] { "Event", "Address", });
    internal_static_register_BroadcastAddress_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_register_BroadcastAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_register_BroadcastAddress_descriptor,
        new java.lang.String[] { "Event", "Addresses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
